version: "3.8"

services:
  vectordb:
    image: pgvector/pgvector:pg15
    ports:
      - 5432:5432
    # restart: always
    environment:
      POSTGRES_DB: vectordb
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: testpwd
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/
      TZ: "US/Central"
    volumes:
      - vectordb_data:/var/lib/postgresql/data
      - ${PWD}/app/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d vectordb -U my_user"]
      interval: 10s
      timeout: 5s
      retries: 5
  

volumes:
  vectordb_data:
